NDefines.NGame.START_DATE = "2022.2.11"
NDefines.NGame.END_DATE = "9999.12.31"
NDefines.NGame.MAX_RANDOM_NEW_WORLD = "1.1.1"
NDefines.NGame.DAYS_BEHIND_LOWER_SPEED = 20			-- In multiplayer if the slowest player is lagging behind this amount of days the game will slow down
NDefines.NDiplomacy.VASSALIZE_BASE_DEVELOPMENT_CAP = 350
NDefines.NDiplomacy.DEFENDER_OF_FAITH_COST = 20000 					-- _DDEF_DEFENDER_OF_FAITH_COST_
NDefines.NDiplomacy.NUM_OF_GREAT_POWERS = 15					-- The number of ordinary (i.e. non-leaving) Great Powers if RightsOfManDLC is enabled.
NDefines.NDiplomacy.RIVAL_DISTANT_WAR_FACTOR = 0.15			-- How much the distant war modifer is reduced when calling against rivals
NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 5
NDefines.NDiplomacy.KNOWLEDGE_SHARING_INSTITUTION_GROWTH_MONTHLY = 4.0
NDefines.NDiplomacy.KNOWLEDGE_SHARING_DURATION_YEARS = 5
NDefines.NDiplomacy.PEACE_COST_RELEASE_VASSAL = 0.25					-- Release vassal (scales by province wealth)
NDefines.NDiplomacy.PEACE_COST_REVOKE_ELECTOR = 30					-- Revoke an elector title
NDefines.NDiplomacy.PEACE_COST_GOLD_STEP = 10 						-- _DDEF_PEACE_COST_GOLD_STEP_ Peace Cost for 1 loan size gold of giver
NDefines.NDiplomacy.PEACE_COST_GOLD_MAX = 10						-- Maximum loans of gold that can be demanded from giver in peace.
NDefines.NDiplomacy.PEACE_COST_CHANGE_GOVERNMENT = 25 				-- _Peace cost for changing government form
NDefines.NDiplomacy.PEACE_COST_TRADE_POWER = 20 					-- Peace cost for demanding trade power
NDefines.NDiplomacy.PEACE_COST_STEER_TRADE = 40					-- Peace cost for steering trade
NDefines.NDiplomacy.INFILTRATE_ADMINISTRATION_COST = 5
NDefines.NDiplomacy.PEACE_COST_INDEPENDANCE = 25 					-- Peace cost for breaking free of union
NDefines.NDiplomacy.PEACE_COST_ENFORCED_FLEET_BASING_RIGHTS = 5   -- Peace cost for enforced fleet basing righs
NDefines.NDiplomacy.PEACE_COST_ENFORCED_MILITARY_ACCESS = 5       -- Peace cost for enforced military access
NDefines.NDiplomacy.PEACE_COST_WAR_REPARATIONS = 10				-- Peace cost for war reparations
NDefines.NDiplomacy.PEACE_COST_GIVE_UP_CLAIM = 10					-- Peace cost for giving up all claims in a country
NDefines.NDiplomacy.PEACE_COST_HUMILIATE_RIVAL = 20
NDefines.NDiplomacy.PEACE_COST_END_RIVALRY = 15
NDefines.NDiplomacy.MAX_PEACE_COST_TRIBUTARY_STATE = 75
NDefines.NDiplomacy.MAX_PEACE_COST_CANCEL_SUBJECT = 60
NDefines.NDiplomacy.SUPPORT_REBELS_EFFECT = 1000
NDefines.NDiplomacy.SUPPORT_REBELS_MONEY_FACTOR = 50
NDefines.NDiplomacy.SUPPORT_REBELS_COST = 30
NDefines.NDiplomacy.DIPLOMAT_SPEED = 200.0							-- DIPLOMAT_SPEED
NDefines.NDiplomacy.DIPLOMAT_COOLDOWN_TIME = 0						-- DIPLOMATIC ACTION COOLDOWN IN MONTHS
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NDiplomacy.SUPPORT_REBELS_DURATION = 1 -- in years
NDefines.NDiplomacy.RIVAL_TRUST_EQUILIBRIUM = 10
NDefines.NDiplomacy.GREAT_POWER_SUBJECT_CONTRIBUTION = 0.1			-- Share of subjects' development that will count towards overlord's Great Power score.
NDefines.NDiplomacy.FABRICATE_CLAIM_COST = 40
NDefines.NDiplomacy.CONDOTTIERI_MIN_DURATION = 12					-- Minimum duration for Condottieri agreements that must be paid for in advance and that cannot be cancelled.
NDefines.NDiplomacy.FABRICATE_CLAIM_COST_MODIFIER_PER_CLAIM = 0.1
NDefines.NCountry.ADVISOR_COST_INCREASE_PER_YEAR = 0.002
NDefines.NCountry.ADVISOR_MIN_DEFAULT_AGE = 25				--Default value used for defining new advisors in script
NDefines.NCountry.LAND_FORCELIMIT_EXTRA_COST_FACTOR = 3		-- extra expense for being above forcelimit
NDefines.NCountry.ADVISOR_MAX_DEFAULT_AGE = 75			--Default value used for defining new advisors in script
NDefines.NCountry.ADVISOR_MAX_DEFAULT_AGE = 75			--Default value used for defining new advisors in script
NDefines.NCountry.PARLIAMENT_RESET_COOLDOWN = 15
NDefines.NCountry.FREE_IDEA_GROUP_COST  = 10
NDefines.NCountry.RIVAL_TECH_THRESHOLD = 0.1						-- Difference in tech group cost modifiers
NDefines.NCountry.STRENGTHEN_GOVERNMENT_LEGITIMACY = 5
NDefines.NCountry.STRENGTHEN_GOVERNMENT_REPUBLICAN_TRADITION = 5
NDefines.NCountry.INSTITUTION_BONUS_FROM_IMP_DEVELOPMENT = 3
NDefines.NCountry.INSTITUTION_CAP_IMP_DEVELOPMENT = 5
NDefines.NCountry.REVOLT_SIZE_DEVELOPMENT_MULTIPLIER = 0.2		-- Multiplied with the province's development
NDefines.NCountry.INSTITUTION_BASE_IMP_DEVELOPMENT = 15
NDefines.NCountry.GREAT_PROJECT_MANPOWER_REQUIRED_FOR_CONSTRUCTION_BOOST = 15000 --use a bunch of manpower to move things on
NDefines.NCountry.GREAT_PROJECT_MANPOWER_CONSTRUCTION_BOOST_AMOUNT_IN_DAYS = 365 --how far throwing men at the problem gets you
NDefines.NCountry.GREAT_PROJECT_MONEY_REQUIRED_FOR_CONSTRUCTION_BOOST = 5000 --use a bunch of money to move things on
NDefines.NCountry.GREAT_PROJECT_MONEY_CONSTRUCTION_BOOST_AMOUNT_IN_DAYS = 365 --how far throwing cash at the problem gets you
NDefines.NCountry.PS_BUY_IDEA = 350
NDefines.NCountry.HIGH_LIBERTY_DESIRE = 65						-- Limit for when a subject starts getting rebellious from liberty desire (also used for alert)
NDefines.NCountry.CORRUPTION_FROM_BANNERS = 40
NDefines.NCountry.TRADE_FAVORS_FOR_GOLD_FAVOR_COST = 25
NDefines.NCountry.TRADE_FAVORS_FOR_GOLD_REQUIRED_OPINION = 100
NDefines.NCountry.TRADE_FAVORS_FOR_MEN_FAVOR_COST = 30
NDefines.NCountry.TRADE_FAVORS_FOR_SAILORS_FAVOR_COST = 30
NDefines.NCountry.PS_ADVANCE_TECH = 500
NDefines.NCountry.PS_BOOST_STABILITY = 150
NDefines.NCountry.PS_CHANGE_CULTURE = 25
NDefines.NCountry.PS_REDUCE_INFLATION = 300
NDefines.NCountry.PS_IMPROVE_PROVINCE_BASE = 60
NDefines.NCountry.PS_REDUCE_WAREXHAUSTION = 125
NDefines.NCountry.REVOLT_TECH_IMPACT = 0.01
NDefines.NCountry.REVOLT_TECH_MORALE = 0.01
NDefines.NCountry.PS_BUY_GENERAL = 100
NDefines.NCountry.PS_BUY_ADMIRAL = 100
NDefines.NCountry.PS_BUY_CONQUISTADOR = 50
NDefines.NCountry.PS_BUY_EXPLORER = 50
NDefines.NCountry.MIN_DEVELOPMENT_FOR_GOV_RANK_2 = 500		-- Need at least this much development to upgrade to government rank 2
NDefines.NCountry.MIN_DEVELOPMENT_FOR_GOV_RANK_3 = 2000		-- Need at least this much development to upgrade to government rank 3
NDefines.NCountry.REBEL_ARTILLERY_INCREASE_LEVEL_1_TECH = 3
NDefines.NCountry.REBEL_ARTILLERY_INCREASE_LEVEL_1_SIZE = 0.0	-- The increase in artillery as fraction of total troops given to rebels
NDefines.NCountry.REBEL_ARTILLERY_INCREASE_LEVEL_2_TECH = 25
NDefines.NCountry.REBEL_ARTILLERY_INCREASE_LEVEL_2_SIZE = 0.1	-- The increase in artillery as fraction of total troops given to rebels (does not stack with level 1)
NDefines.NCountry.GALLEY_INLAND_SEA_COAST_RATIO = 0.75 			-- % of ports that need to be inland seas for galleys to be considered important
NDefines.NCountry.MIN_TECH_FOR_CIRCUMNAVIGATE = 9
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_1 = 226			-- Provinces for circumnavigation (Jebal Al Tareq Channel)
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_2 = 4438			-- Provinces for circumnavigation (Suez)
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_3 = 388			-- Provinces for circumnavigation (Adan)
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_4 = 3141			-- Provinces for circumnavigation (Hurmuz)
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_5 = 2008			-- Provinces for circumnavigation (Singapor)
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_6 = 835			-- Provinces for circumnavigation (Panama)
NDefines.NCountry.HORDE_RAZE_TECH_BASE_LEVEL = 9
NDefines.NCountry.IDEA_TO_TECH = 0.00
NDefines.NCountry.TECH_TIME_COST = 1.0
NDefines.NCountry.HRE_RANK = 2							-- Emperor of the HRE is displayed as this rank (for ruler title only)
NDefines.NCountry.HRE_MAX_RANK = 2							-- for members
NDefines.NCountry.ARMY_PROFESSIONALISM_PER_AGE = 0.08
NDefines.NCountry.INNOVATIVENESS_FIRST_REACHED_TECH_LEVEL = 3.0  -- Innovativeness bonus to first country (or countries) to reach a certain tech level.
NDefines.NCountry.INNOVATIVENESS_FIRST_PICKED_IDEA = 1.0			-- Innovativeness bonus to first country (or countries) to pick an idea.
NDefines.NCountry.INNOVATIVENESS_BEHIND_IN_TECH_PENALTY = -0.03 	-- Innovativeness penalty if behind neighbors in tech (and not ahead of time).
NDefines.NCountry.INNOVATIVENESS_AHEAD_OF_TIME_BONUS = 0.01 -- Bonus for being ahead of time in tech
NDefines.NCountry.INNOVATIVENESS_ENABLE_ANY_BEHIND_IN_TECH_PENALTY = -0.01	-- Enabled that if any tech is behind we apply the penalty. Turning this off will require you only to be ahead in one.
NDefines.NCountry.INNOVATIVENESS_ENABLE_PER_TECH_BEHIND_IN_TECH_PENALTY = -0.01 -- Enable that the penalty is applied for each tech we are behind in tech.
NDefines.NCountry.INNOVATIVENESS_DAYS_AFTER_FIRST_PICK_VIABLE = 400 -- How many days you can still get innov
NDefines.NCountry.INNOVATIVENESS_MAX = 100.0 -- Innovativeness Cap
NDefines.NCountry.STARTING_ARMY_SIZE = 1.0						-- Percentage of force limit
NDefines.NCountry.STARTING_FLEET_SIZE = 0.0
NDefines.NCountry.STATE_MAINTENANCE_DEV_FACTOR = 0.045		-- per dev
NDefines.NCountry.STATE_MAINTENANCE_DISTANCE_FACTOR = 0.003	-- distance
NDefines.NCountry.STATE_MAINTENANCE_CONTINENT_FACTOR = 0.05	-- different continet
NDefines.NCountry.STATE_MAINTENANCE_CULTURE_FACTOR = 0.35		-- non accepted culture
NDefines.NCountry.POWER_MAX = 2000								-- how much power can be stored at maximum.
NDefines.NCountry.MONARCH_MAX_SKILL = 7
NDefines.NCountry.CONVERSION_COOLDOWN = 720						-- months before you can convert again.
NDefines.NCountry.CONVERSION_COOLDOWN_SECONDARY = 720			-- months before you can convert secondary religion again.
NDefines.NCountry.TRADING_POLICY_COOLDOWN_MONTHS  = 12			-- Cooldown until you can change Trading Policy after selecting.
NDefines.NCountry.MAXIMUM_ADVISOR_SKILL = 10						-- Maximum advisor skill reachable through promotion
NDefines.NCountry.MAXIMUM_CONDOTTIERI = 50					-- Base number of units you can rent out
NDefines.NCountry.CORRUPTION_COST = 0.2						-- cost for monthly combat per development
NDefines.NCountry.MAX_EXTRA_PERSONALITIES = 4					-- Number of personalities that can be gained except the one you get when turning 15.
NDefines.NCountry.FIRST_EXTRA_PERSONALITY = 4					-- Number of years after inauguration that first extra personality is gained.
NDefines.NCountry.YEARS_PER_EXTRA_PERSONALITY = 3				-- Number of years between new personalities after first one.
NDefines.NCountry.PROVINCE_DISCOVERY_YEARS_TECHNOLOGY = 2		-- Years until discoveries spread within technology group
NDefines.NCountry.PROVINCE_DISCOVERY_YEARS_RELIGION = 2		-- Years until discoveries spread with religion
NDefines.NCountry.EMBRACE_INSTITUTION_COST = 22				-- 2.5 per development (autonomy modified)
NDefines.NCountry.BASE_POSSIBLE_POLICIES = 4						-- How many policies in a category a nation can have as a base
NDefines.NCountry.BASE_POWER_INCREASE = 8				-- monthly base increase Poit Skill ( Base )
NDefines.NEconomy.EDICTS_COST_INCREASE = 0.5				-- % increase on state maintenance.
NDefines.NEconomy.EDICTS_DURATION_MONTHS = 60				-- months lastin at least.
NDefines.NEconomy.DEBASE_MAX_CORRUPTION = 20						-- Above this level of corruption you won't be able to Debase Currency.
NDefines.NEconomy.LAND_TECH_MAINTENANCE_IMPACT = 0.01
NDefines.NEconomy.BANKRUPTCY_BUILDING_DESTRUCTION_THRESHOLD = 10	-- Bankruptcy will destroy building that have been build in the latest X amount of years. Set to zero to disable the destruction mechanic.
NDefines.NEconomy.NAVAL_TECH_MAINTENANCE_IMPACT = 0.008 			-- % each tech increases it.
NDefines.NEconomy.GOLD_INFLATION = 0.02							-- _EDEF_GOLD_INFLATION_
NDefines.NEconomy.MINIMUM_INTERESTS = 4.0						-- _EDEF_MINIMUM_INTERESTS_
NDefines.NEconomy.BASE_INTERESTS = 20.0							-- Base interests
NDefines.NEconomy.LAND_TECH_MERC_MAINTENANCE_IMPACT = 0.01
NDefines.NEconomy.GOLD_MINE_DEPLETION_THRESHOLD = 0				-- Gold mines above production level or above can be depleted
NDefines.NEconomy.GOLD_MINE_DEPLETION_CHANCE = 0					-- Chance of gold mine being depleted (yearly, per production above threshold)
NDefines.NEconomy.LAND_MAINTENANCE_FACTOR = 0.035					-- _EDEF_LAND_MAINTENANCE_FACTOR
NDefines.NEconomy.HEAVY_SHIP_MAINT_FACTOR = 0.04					-- _EDEF_HEAVY_SHIP_MAINT_FACTOR_
NDefines.NEconomy.LIGHT_SHIP_MAINT_FACTOR = 0.020					-- _EDEF_LIGHT_SHIP_MAINT_FACTOR_
NDefines.NEconomy.GALLEY_MAINT_FACTOR = 0.04						-- _EDEF_GALLEY_MAINT_FACTOR_
NDefines.NEconomy.TRANSPORT_MAINT_FACTOR = 0.25					-- _EDEF_TRANSPORT_MAINT_FACTOR_
NDefines.NEconomy.COLONIAL_MAINTENANCE_FACTOR = 50.0				-- _EDEF_COLONIAL_MAINTENANCE_FACTOR_
NDefines.NEconomy.EMBARGO_BASE_EFFICIENCY = 2					-- EMBARGO_BASE_EFFICIENCY
NDefines.NEconomy.ADVISOR_COST = 7.0								-- Advisor cost modifier			
NDefines.NEconomy.MAX_BUILDING_SLOTS = 18		
NDefines.NEconomy.BESTOW_GIFTS_FRACTION = 2.0					-- As share of target's yearly income	
NDefines.NEconomy.MISSIONARY_MAINTENANCE_FACTOR = 1.0				-- How much a missionary costs in itself
NDefines.NEconomy.MISSIONARY_MAINTENANCE_DEVELOPMENT_FACTOR = 0.75	-- How much this is ncreased from development
NDefines.NEconomy.MISSIONARY_MAINTENANCE_AUTONOMY_FACTOR = 0.75		-- How much this is ncreased from local autonomy
NDefines.NEconomy.MISSIONARY_MAINTENANCE_AUTONOMY_BASE = 3.0			-- The local autonomy is added to this base in the formula.
NDefines.NEconomy.MISSIONARY_MAINTENANCE_DEVELOPMENT_CAP = 30		-- Where dev will get capped by the system for calculations.
NDefines.NMilitary.ARMY_DRILL_SKILL_MONTHS = 24
NDefines.NMilitary.MAX_SAILOR_LACK_ATTRITION = 0
NDefines.NMilitary.ARMY_ATTRITION_AT_COAST = 0
NDefines.NMilitary.ARMY_ATTRITION_AT_SEA = 0						-- How many percent attrition units take while loaded onto ships traveling open sea
NDefines.NMilitary.HEAVY_SHIP_SAILORS_COST = 10000					-- 1 = 1 men in cost.
NDefines.NMilitary.LIGHT_SHIP_SAILORS_COST = 350					-- 1 = 1 men in cost.
NDefines.NMilitary.GALLEY_SHIP_SAILORS_COST = 1000					-- 1 = 1 men in cost.
NDefines.NMilitary.TRANSPORT_SHIP_SAILORS_COST = 200				-- 1 = 1 men in cost.
NDefines.NMilitary.BANNER_STARTING_STRENGTH = 0.5
NDefines.NMilitary.CAWA_STARTING_STRENGTH = 0.5					-- Starting strength of a cawa regiment 1.0 being full strength
NDefines.NMilitary.CAWA_STARTING_MORALE = 0.1						-- Starting morale of a cawa regiment 1.0 being full strength
NDefines.NMilitary.JANISSARIES_STARTING_STRENGTH = 0.1
NDefines.NMilitary.JANISSARIES_STARTING_MORALE = 0.1
NDefines.NMilitary.CREATE_JANISSARIES_MIL_COST = 25				-- Cost to create janissaries (per unit)
NDefines.NMilitary.CREATE_CAWA_MIL_COST = 50						-- Cost to create Cawa (per unit)
NDefines.NMilitary.TERCIO_USES_CONSTRUCTION = 1
NDefines.NMilitary.TERCIO_BASE_COST_MODIFIER = 1.0
NDefines.NMilitary.TERCIO_MANPOWER_COST_MODIFIER = 1.0
NDefines.NMilitary.TERCIO_ARMY_TRADITION_COST = 0
NDefines.NMilitary.TERCIO_STARTING_STRENGTH = 0.5
NDefines.NMilitary.TERCIO_STARTING_MORALE = 0.1 
NDefines.NMilitary.MUSKETEER_USES_CONSTRUCTION = 1
NDefines.NMilitary.MUSKETEER_BASE_COST_MODIFIER = 1.0
NDefines.NMilitary.MUSKETEER_MANPOWER_COST_MODIFIER = 1.0
NDefines.NMilitary.MUSKETEER_PRESTIGE_COST = 0
NDefines.NMilitary.MUSKETEER_ABSOLUTISM_COST = 0
NDefines.NMilitary.MUSKETEER_STARTING_STRENGTH = 0.5
NDefines.NMilitary.MUSKETEER_STARTING_MORALE = 0.1 
NDefines.NMilitary.SAMURAI_USES_CONSTRUCTION = 1
NDefines.NMilitary.SAMURAI_BASE_COST_MODIFIER = 1.0
NDefines.NMilitary.SAMURAI_MANPOWER_COST_MODIFIER = 1.0
NDefines.NMilitary.SAMURAI_LEGITIMACY_COST = 0
NDefines.NMilitary.SAMURAI_STARTING_STRENGTH = 0.5
NDefines.NMilitary.SAMURAI_STARTING_MORALE = 0.1 
NDefines.NMilitary.GEOBUKSEON_USES_CONSTRUCTION = 1
NDefines.NMilitary.GEOBUKSEON_BASE_COST_MODIFIER = 1.0
NDefines.NMilitary.GEOBUKSEON_SAILORS_COST_MODIFIER = 1.5
NDefines.NMilitary.GEOBUKSEON_STARTING_STRENGTH = 0.5
NDefines.NMilitary.GEOBUKSEON_STARTING_MORALE = 1 
NDefines.NMilitary.MAN_OF_WAR_USES_CONSTRUCTION = 1
NDefines.NMilitary.MAN_OF_WAR_BASE_COST_MODIFIER = 1.0
NDefines.NMilitary.MAN_OF_WAR_SAILORS_COST_MODIFIER = 1.5
NDefines.NMilitary.MAN_OF_WAR_STARTING_STRENGTH = 0.5
NDefines.NMilitary.MAN_OF_WAR_STARTING_MORALE = 0.1
NDefines.NMilitary.QIZILBASH_USES_CONSTRUCTION = 1
NDefines.NMilitary.QIZILBASH_BASE_COST_MODIFIER = 0.7
NDefines.NMilitary.QIZILBASH_MANPOWER_COST_MODIFIER = 1.0
NDefines.NMilitary.QIZILBASH_LEGITIMACY_COST = 0
NDefines.NMilitary.QIZILBASH_STARTING_STRENGTH = 1.0
NDefines.NMilitary.QIZILBASH_STARTING_MORALE = 0.1
NDefines.NMilitary.MAMLUKS_USES_CONSTRUCTION = 1
NDefines.NMilitary.MAMLUKS_BASE_COST_MODIFIER = 1.0
NDefines.NMilitary.MAMLUKS_MANPOWER_COST_MODIFIER = 1.0
NDefines.NMilitary.MAMLUKS_LEGITIMACY_COST = 0
NDefines.NMilitary.MAMLUKS_STARTING_STRENGTH = 1.0
NDefines.NMilitary.MAMLUKS_STARTING_MORALE = 0.1
NDefines.NMilitary.GALLEON_USES_CONSTRUCTION = 1
NDefines.NMilitary.GALLEON_BASE_COST_MODIFIER = 1.0
NDefines.NMilitary.GALLEON_SAILORS_COST_MODIFIER = 1.5
NDefines.NMilitary.GALLEON_STARTING_STRENGTH = 0.5
NDefines.NMilitary.GALLEON_STARTING_MORALE = 0.1
NDefines.NMilitary.GALLEASS_USES_CONSTRUCTION = 1
NDefines.NMilitary.GALLEASS_BASE_COST_MODIFIER = 1.0
NDefines.NMilitary.GALLEASS_SAILORS_COST_MODIFIER = 1.5
NDefines.NMilitary.GALLEASS_STARTING_STRENGTH = 0.5
NDefines.NMilitary.GALLEASS_STARTING_MORALE = 0.1
NDefines.NMilitary.CARAVEL_USES_CONSTRUCTION = 1
NDefines.NMilitary.CARAVEL_BASE_COST_MODIFIER = 1.0
NDefines.NMilitary.CARAVEL_SAILORS_COST_MODIFIER = 1.5
NDefines.NMilitary.CARAVEL_STARTING_STRENGTH = 0.5
NDefines.NMilitary.CARAVEL_STARTING_MORALE = 0.1
NDefines.NMilitary.VOC_INDIAMEN_USES_CONSTRUCTION = 1
NDefines.NMilitary.VOC_INDIAMEN_BASE_COST_MODIFIER = 1.0
NDefines.NMilitary.VOC_INDIAMEN_SAILORS_COST_MODIFIER = 1.5
NDefines.NMilitary.VOC_INDIAMEN_STARTING_STRENGTH = 0.5
NDefines.NMilitary.VOC_INDIAMEN_STARTING_MORALE = 0.1 
NDefines.NMilitary.STRELSKY_STARTING_STRENGTH = 0.5
NDefines.NMilitary.COSSACKS_STARTING_STRENGTH = 0.5
NDefines.NMilitary.MARINES_STARTING_STRENGTH = 0.5
NDefines.NMilitary.RAJPUT_STARTING_STRENGTH = 0.5
NDefines.NMilitary.REVOLUTIONARY_GUARD_STARTING_STRENGTH = 0.5
NDefines.NMilitary.STRELTSY_BASE_COST_MODIFIER = 1.0
NDefines.NMilitary.STRELTSY_MANPOWER_COST_MODIFIER = 1.0
NDefines.NMilitary.STRELTSY_STARTING_MORALE = 0.1
NDefines.NMilitary.CAROLEAN_STARTING_STRENGTH = 0.5
NDefines.NMilitary.CAROLEAN_STARTING_MORALE = 0.8
NDefines.NMilitary.CAROLEAN_BASE_COST_MODIFIER = 6.0
NDefines.NMilitary.BASE_MP_TO_MANPOWER = 0.50		-- 250 men per manpower
NDefines.NMilitary.BASE_COMBAT_WIDTH = 2.0
NDefines.NMilitary.MAX_COMBAT_WIDTH = 40
NDefines.NMilitary.INFANTRY_SPEED = 1.7 							-- _MDEF_INFANTRY_SPEED = 10
NDefines.NMilitary.CAVALRY_SPEED = 3.1 							-- _MDEF_CAVALRY_SPEED = 10
NDefines.NMilitary.ARTILLERY_SPEED = 1.4							-- _MDEF_ARTILLERY_SPEED = 10
NDefines.NMilitary.INFANTRY_COST = 150.0 							-- _MDEF_INFANTRY_COST = 10
NDefines.NMilitary.CAVALRY_COST = 225.0 							-- _MDEF_CAVALRY_COST = 10
NDefines.NMilitary.ARTILLERY_COST = 300.0 							-- _MDEF_ARTILLERY_COST = 10
NDefines.NMilitary.FORTRESS_COST = 5.0								-- base fort cost
NDefines.NMilitary.HEAVY_SHIP_COST = 33000 							-- _MDEF_HEAVY_SHIP_COST = 10
NDefines.NMilitary.LIGHT_SHIP_COST = 6000							-- _MDEF_LIGHT_SHIP_COST = 10
NDefines.NMilitary.GALLEY_COST = 3300 								-- _MDEF_GALLEY_COST = 10
NDefines.NMilitary.TRANSPORT_COST = 100							-- _MDEF_TRANSPORT_COST = 10
NDefines.NMilitary.HEAVY_SHIP_TIME = 2000 							-- _MDEF_HEAVY_SHIP_TIME = 10
NDefines.NMilitary.LIGHT_SHIP_TIME = 700 							-- _MDEF_LIGHT_SHIP_TIME = 10
NDefines.NMilitary.GALLEY_TIME = 700 								-- _MDEF_GALLEY_TIME = 10
NDefines.NMilitary.TRANSPORT_TIME = 45 							-- _MDEF_TRANSPORT_TIME = 10
NDefines.NMilitary.RAJPUT_BASE_COST_MODIFIER = 4.0				-- Rajput base cost is double as expensive
NDefines.NMilitary.COSSACK_BASE_COST_MODIFIER = 2.0				-- Cossack base cost is double as expensive
NDefines.NMilitary.BANNER_USES_CONSTRUCTION = 1
NDefines.NMilitary.CAWA_USES_CONSTRUCTION = 1
NDefines.NMilitary.JANISSARIES_USES_CONSTRUCTION = 1
NDefines.NMilitary.MIN_MONTHLY_SAILORS = 250
NDefines.NMilitary.COMBAT_DICE_SIDE = 6
NDefines.NMilitary.NAVAL_SUPPLY_RANGE = 500 						-- Supply range for ships.
NDefines.NMilitary.SIEGE_WIN = 15
NDefines.NMilitary.MONTHS_BEFORE_TOTAL_OCCUPATION = 12
NDefines.NMilitary.DAYS_PER_PHASE = 2
NDefines.NMilitary.MERCENARY_COMPANY_MIN_REGIMENTS = 1			-- Minimum regiments
NDefines.NMilitary.MERCENARY_COMPANY_MAX_REGIMENTS = 160			-- Maximum regiments
NDefines.NMilitary.CAV_SUPPRESSION = 0.30						-- The amount of reduction to unrest for each friendly cavalry regiment in a province
NDefines.NMilitary.ART_SUPPRESSION = 0.35						-- The amount of reduction to unrest for each friendly artillery regiment in a province
NDefines.NMilitary.HEAVY_SHIP_COMBAT_WIDTH = 5
NDefines.NMilitary.MOTHBALLING_MINIMUM_STRENGTH = 0.4				-- The minimum strength value the fleet will reach while mothballin
NDefines.NMilitary.LEADER_MAX_PIPS = 10							-- Max general/admiral pips (per skill)
NDefines.NMilitary.LEADER_MIN_PIPS = 1							-- Min general/admiral pips (total)
NDefines.NMilitary.FLAGSHIP_COST_DUCATS = 40000						-- The cost in ducats of a flagship
NDefines.NMilitary.FLAGSHIP_COST_SAILORS = 5000				-- The cost in sailors of a flagship
NDefines.NMilitary.FLAGSHIP_BUILDTIME = 3650					-- Building time in days of a flagship
NDefines.NMilitary.EXPLORER_LEADER_POWER = 0.5
NDefines.NMilitary.CONDOTTIERI_TRADITION_BONUS = 1.0				-- This modifies army tradition gained from fighting with condottieris
NDefines.NMilitary.WARDEC_COBELLI_FOR_HOLY_ROMAN_EMPEROR = 1
NDefines.NMilitary.SUPPLYLIMIT_BASE_MULTIPLIER = 6.0 				--
NDefines.NMilitary.WARGOAL_MAX_BONUS = 55
NDefines.NAI.ONLY_INFANTRY_MERCS = 1 --Set to 0 to let AI hire artillery and cavalry mercenaries.
NDefines.NAI.BASE_CAN_MAKE_CORE_DESIRE_TO_RETURN_PROVINCE = 15
NDefines.NAI.CORRUPTION_BUDGET_FRACTION = 1.0 -- AI will spend a maximum of this fraction of monthly income on rooting out corruption
NDefines.NAI.FORCE_COMPOSITION_CHANGE_TECH_LEVEL = 3 -- Tech level at which AI will double its artillery fraction
NDefines.NAI.DIPLOMATIC_INTEREST_DISTANCE = 300
NDefines.NAI.PEACE_DESIRE_AI_PREFS_QUICK_PEACE = 55
NDefines.NAI.CONQUEST_INTEREST_DISTANCE = 2000
NDefines.NAI.REPAY_LOAN_BASE_AI_DESIRE = 2000.0  -- AI scoring for repaying loans multiplied by (MAX(budget - other loans 0) * number_of_loans)/cost
NDefines.NAI.DIPLOMATIC_ACTION_CLAIM_THRONE_MAX_DISTANCE = 2500
NDefines.NAI.DIPLOMATIC_ACTION_WARNING_MAX_DISTANCE = 2500
NDefines.NAI.ACCEPTABLE_BALANCE_DEFAULT = 0.6
NDefines.NAI.ACCEPTABLE_BALANCE_MULT_FRIEND_IN_COMBAT = 0.3
NDefines.NAI.ACCEPTABLE_BALANCE_MULT_OFFENSIVE = 6.5
NDefines.NAI.ACCEPTABLE_BALANCE_THREAT_WEIGHT = 0.6
NDefines.NAI.DEVELOPMENT_CAP_BASE = 15
NDefines.NAI.DEVELOPMENT_CAP_MULT = 5
NDefines.NAI.DRILLING_DEBT_SURPLUS_RATIO_THRESHOLD = 0.9				-- AI will only consider drilling if Surplus / Debt ratio is above
NDefines.NAI.TRANSPORT_FRACTION = 0.25 -- Max fraction of naval forcelimit that should be transports
NDefines.NAI.MIN_SHIPS_FOR_ADMIRAL = 15 -- The minimum navy size for the AI to bother with an admiral
NDefines.NAI.DRILLING_BUDGET_OF_SURPLUS = 0.8						-- Max amount of surplus to be used for drilling
NDefines.NAI.DIPLOMATIC_ACTION_COALITION_DISTANCE_FACTOR = 2000 -- AI scoring for joining/forming coalition based on distance
NDefines.NAI.DIPLOMATIC_ACTION_COALITION_SIZE_FACTOR_MAX = 1000 -- Size factor will not go above this regardless of number of cities
NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_ONLY_MILITARY_RULERS = 0 --If set to 1 AI will only send Condottieri while having a miliaristic ruler.
NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_ONLY_NEIGHBORS = 0 --If set to 1 AI will only send Condottieri to neighbors regardless of access.
NDefines.NAI.DIPLOMATIC_ACTION_TAKE_ON_DEBT_POWERBALANCE_FACTOR = 25
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_BASE_FACTOR = 80
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_STRATEGY_FACTOR = 1.2
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_OTHER_CB_FACTOR = 0.3
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_NOT_ADJACENT_FACTOR = 0.75
NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_POWERBALANCE_FACTOR = 80
NDefines.NAI.DIPLOMATIC_ACTION_GIFT_POWERBALANCE_FACTOR_AI = 100
NDefines.NAI.DIPLOMATIC_ACTION_GIFT_POWERBALANCE_FACTOR_PLAYER = 85
NDefines.NAI.DIPLOMATIC_ACTION_GUARANTEE_POWERBALANCE_FACTOR = 100
NDefines.NAI.DIPLOMATIC_ACTION_MILITARY_ACCESS_EXISTING_RELATION_MULT = 10.0
NDefines.NAI.DIPLOMATIC_ACTION_MILITARY_ACCESS_ENEMY_REGIMENTS_FACTOR = 20.0
NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_WAR_WITH_RIVAL_FACTOR = 100
NDefines.NAI.PEACE_SWING_PANIC_THRESHOLD = 0.5 -- If a new entrant to a war will swing us from a winning position to a position worse than this, we'll consider accepting an enforce peace action a bit more seriously
NDefines.NAI.PEACE_PANIC_FACTOR = 300 --the amount we'll swing if we start panicking (multiplied by the amount under the panic swing threshold we will now be)
NDefines.NAI.HOME_FLEET_MAX_RATIO = 0.8							-- Maximum proportion of warships in home fleet.
NDefines.NAI.ADVISOR_PROMOTION_AGE_CUTOFF = 65							-- AI will not promote advisors above this age
NDefines.NAI.MAX_BUILDING_COST_INCOME_MONTHS = 36.0
NDefines.NAI.INCOME_SAVINGS_FRACTION = 0.30
NDefines.NAI.AGGRESSIVENESS = 100 -- Base chance (out of 10000) of AI being willing to start a war each diplomatic tick (~1.5 times a month)
NDefines.NAI.AGGRESSIVENESS_BONUS_EASY_WAR = 150 -- Added to aggressiveness if the war is against a weak or particularily hated enemy
NDefines.NAI.EXTRA_SURPLUS_WHEN_NEEDING_BUILDINGS = 0.20
NDefines.NAI.ESTATE_MAX_WANTED_INFLUENCE = 90.0
NDefines.NAI.ESTATE_MIN_WANTED_CROWNLAND = 10.0
NDefines.NAI.DANGEROUS_ESTATE_INFLUENCE_BUFFER = 6.5
NDefines.NAI.MISSION_PICK_CHANCE = 50.0
NDefines.NAI.PS_SHORT_TERM_POOL = 250.0
NDefines.NAI.PEACE_DESPERATION_FACTOR = 30
NDefines.NAI.PEACE_REBELS_FACTOR = 25
NDefines.NAI.PEACE_ALLY_REBELS_MULT = 1.1
NDefines.NAI.PEACE_COALITION_FACTOR = 25
NDefines.NAI.PEACE_CAPITAL_FACTOR = 10
NDefines.NAI.PEACE_CALL_FOR_PEACE_FACTOR = 50
NDefines.NAI.PEACE_TIME_MONTHS = 75
NDefines.NAI.PEACE_BASE_RELUCTANCE = 5
NDefines.NAI.PEACE_MILITARY_STRENGTH_FACTOR = 25
NDefines.NAI.PEACE_HIGH_WAR_EXHAUSTION_FACTOR = 3.0
NDefines.NAI.PEACE_WAR_EXHAUSTION_FACTOR = 0.65
NDefines.NAI.PEACE_TERMS_STRATEGY_MULT = 0.65
NDefines.NAI.PEACE_TERMS_BASE_SCORE = 15
NDefines.NAI.PEACE_EXCESSIVE_DEMANDS_THRESHOLD = 33
NDefines.NAI.PEACE_EXCESSIVE_DEMANDS_FACTOR = 0.005
NDefines.NAI.PEACE_TERMS_PROVINCE_IMPERIAL_LIBERATION_MULT = 5.0
NDefines.NAI.PEACE_TERMS_PROVINCE_NO_CB_MULT = 0.9
NDefines.NAI.PEACE_TERMS_PROVINCE_CORE_MULT = 4.0
NDefines.NAI.PEACE_TERMS_PROVINCE_WARGOAL_MULT = 2.2
NDefines.NAI.PEACE_TERMS_PROVINCE_CLAIM_MULT = 5.0
NDefines.NAI.PEACE_TERMS_PROVINCE_NOT_CULTURE_MULT = 0.9
NDefines.NAI.PEACE_TERMS_PROVINCE_NO_INTEREST_MULT = 0
NDefines.NAI.PEACE_TERMS_PROVINCE_VASSAL_MULT = 1.0
NDefines.NAI.PEACE_TERMS_RELEASE_VASSALS_BASE_MULT = 0.9
NDefines.NAI.PEACE_TERMS_TRANSFER_VASSALS_BASE_MULT = 0.8
NDefines.NAI.PEACE_TERMS_PROVINCE_REAL_ADJACENT_MULT = 1.5
NDefines.NAI.PEACE_TERMS_RETURN_CORES_VASSAL_MULT = 10.0
NDefines.NAI.ASSIMILATION_INTEREST_AMOUNT_FACTOR = 1000.0
NDefines.NAI.ARMY_DISTANCE_SCORE_IMPACT	= 0.1
NDefines.NAI.BORDER_DISTANCE_SCORE_IMPACT = 0.2
NDefines.NAI.PURSUE_DISTANCE = 100
NDefines.NAI.INVADING_MAX_AWAY_RATIO = 0.5
NDefines.NAI.INVADING_BRAVERY = 1.2
NDefines.NAI.INVASION_ARMY_LOOKUP_INTERVAL_ON_FAILURE = 15
NDefines.NAI.WAR_MIN_WARSCORE_TO_JOIN = -35
NDefines.NAI.REGION_PLANNING_HOMELAND_PRIORIZATION = 25.0
NDefines.NAI.MIN_FORCE_LIMIT_SHARE_REGION_ASSIGN = 0.2
NDefines.NAI.MAX_ARMIES_NEW_REGION_ASSIGN_ALGORITHM = 40
NDefines.NAI.MAX_TASKS_NEW_REGION_ASSIGN_ALGORITHM = 100
NDefines.NAI.OVER_FORCELIMIT_AVOIDANCE_FACTOR = 60.0
NDefines.NAI.MIN_CAV_PERCENTAGE = 10
NDefines.NAI.MAX_CAV_PERCENTAGE = 50
NDefines.NAI.REGIMENTS_PER_GENERAL = 25
NDefines.NAI.IMPORANT_PROVINCE_THRESHOLD = 0.06
NDefines.NAI.DESIRED_DEFICIT = 0.01
NDefines.NAI.DESIRED_SURPLUS = 0.05
NDefines.NAI.CHARTER_COMPANY_BASE_RELUCTANCE = -1000
NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS = 3
NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS_PEACETIME = 24.0
NDefines.NAI.ADVISOR_MIN_SKILL_RELUCTANT_FIRE = 4
NDefines.NAI.COLONY_BUDGET_FRACTION = 0.2
NDefines.NAI.NOMINAL_ARMY_SIZE_MULTIPLIER = 1.15
NDefines.NAI.FORT_CAPITAL_DESIRE = 1000.0
NDefines.NAI.FORT_ON_BORDER_MULT = 1.79
NDefines.NAIEconomy.BUDGETING_ADJUSTMENT_STEP = 0.5
NDefines.NAIEconomy.REBEL_THREAT_MILITARIZE_THRESHOLD = 1.0
NDefines.NAIEconomy.MILITARY_FOCUS_LOWER_BOUND = 3.0
NDefines.NAIEconomy.MILITARY_FOCUS_UPPER_BOUND = 4.5
NDefines.NAIEconomy.ARMY_FRACTION_PEACEFUL = 2.1
NDefines.NAIEconomy.ARMY_FRACTION_MILITARIST = 4.35
NDefines.NAIEconomy.ARMY_FRACTION_MILITARIZE = 2.2
NDefines.NAIEconomy.NAVY_FRACTION_PEACEFUL = 2.0
NDefines.NAIEconomy.NAVY_FRACTION_CAPITALIST = 2.0
NDefines.NAIEconomy.FORT_FRACTION_MILITARIST = 4.0
NDefines.NAIEconomy.FORT_FRACTION_CAPITALIST = 7.0
NDefines.NAIEconomy.FORT_FRACTION_MILITARIZE = 6.0
NDefines.NAIEconomy.MISSIONARY_FRACTION = 1.0
NDefines.NAIEconomy.STATE_MAINTENANCE_FRACTION = 0.175
NDefines.NGraphics.BORDER_WIDTH = 0.6
NDefines.NFrontend.CAMERA_END_X = 500.0	-- Move to position in main menu
NDefines.NFrontend.CAMERA_LOOKAT_X = 150.0 	
NDefines.NFrontend.CAMERA_LOOKAT_Y = 1000.0
NDefines.NFrontend.CAMERA_LOOKAT_Z = 1519.0
NDefines.NFrontend.CAMERA_END_Y = 830.0
NDefines.NFrontend.CAMERA_MIN_HEIGHT = 55.0	
NDefines.NFrontend.CAMERA_MAX_HEIGHT = 4000.0
NDefines.NGovernment.GOVERNMENT_REFORM_BASE_COST = 0.0
NDefines.NGovernment.GOVERNMENT_REFORM_COST_INCREASE = 0.0
NDefines.NGovernment.GOVERNMENT_REFORM_YEARLY_BASE_PROGRESS = 10.0
NDefines.NGovernment.GOVERNMENT_REFORM_CHANGE_PROGRESS_COST = 200.0